[2013-03-22 11:32:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Compile Error: Cannot override final method App\Controllers\Api\Common\BaseApiController::validateInput() in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php line 22' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php:22
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-22 11:33:05] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'subcardCode' in 'field list' (SQL: insert into `order_models` (`store_model_id`, `total`, `commissionRate`, `paymentMethod`, `isDelivered`, `credit`, `comment`, `subcardCode`, `due_at`, `ip`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => '1',
  1 => 14.47,
  2 => '0.05',
  3 => 'cash',
  4 => false,
  5 => 0,
  6 => '',
  7 => '',
  8 => 
  DateTime::__set_state(array(
     'date' => '2013-03-22 11:53:19',
     'timezone_type' => 3,
     'timezone' => 'Europe/Berlin',
  )),
  9 => '127.0.0.1',
  10 => 
  DateTime::__set_state(array(
     'date' => '2013-03-22 11:33:05',
     'timezone_type' => 3,
     'timezone' => 'Europe/Berlin',
  )),
  11 => 
  DateTime::__set_state(array(
     'date' => '2013-03-22 11:33:05',
     'timezone_type' => 3,
     'timezone' => 'Europe/Berlin',
  )),
))' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Database/Connection.php:483
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Database/Connection.php(456): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `or...', Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Database/Connection.php(309): Illuminate\Database\Connection->run('insert into `or...', Array, Object(Closure))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Database/Connection.php(266): Illuminate\Database\Connection->statement('insert into `or...', Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `or...', Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1083): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `or...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(450): call_user_func_array(Array, Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(8653): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(8653): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(8606): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/models/BaseModel.php(36): Illuminate\Database\Eloquent\Model->save()
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(145): App\Models\BaseModel->save()
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(43): App\Controllers\Api\Frontend\Customer\Orders\CreateController->saveOrderModel()
#13 [internal function]: App\Controllers\Api\Frontend\Customer\Orders\CreateController->route('memmingen')
#14 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#15 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#16 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen')
#18 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#19 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#20 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#24 {main} [] []
[2013-03-22 12:37:39] log.ERROR: exception 'ErrorException' with message 'Warning: Missing argument 1 for App\Controllers\Api\Common\BaseApiController::throwException(), called in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/authentification/CheckTokenController.php on line 20 and defined in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php line 55' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php:55
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php(55): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'Missing argumen...', '/Users/johannes...', 55, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/authentification/CheckTokenController.php(20): App\Controllers\Api\Common\BaseApiController->throwException()
#2 [internal function]: App\Controllers\Api\Frontend\Authentification\CheckTokenController->route()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-22 12:40:21] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: input in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php line 217' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php:217
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(217): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/Users/johannes...', 217, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(64): App\Controllers\Api\Frontend\Customer\Orders\CreateController->validateInputArrayStructure()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(35): App\Controllers\Api\Frontend\Customer\Orders\CreateController->checkInput()
#3 [internal function]: App\Controllers\Api\Frontend\Customer\Orders\CreateController->route('memmingen')
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen')
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2013-03-22 12:41:28] log.ERROR: exception 'ErrorException' with message 'Warning: Missing argument 1 for App\Controllers\Api\Common\BaseApiController::throwException(), called in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/authentification/CheckTokenController.php on line 20 and defined in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php line 55' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php:55
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php(55): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'Missing argumen...', '/Users/johannes...', 55, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/authentification/CheckTokenController.php(20): App\Controllers\Api\Common\BaseApiController->throwException()
#2 [internal function]: App\Controllers\Api\Frontend\Authentification\CheckTokenController->route()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-22 13:10:15] log.ERROR: exception 'ErrorException' with message 'Notice: Array to string conversion in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php line 295' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php:295
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(295): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Array to string...', '/Users/johannes...', 295, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(81): App\Controllers\Api\Frontend\Customer\Orders\CreateController->checkIngredientModelIdsAreValid()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(37): App\Controllers\Api\Frontend\Customer\Orders\CreateController->checkModelIds()
#3 [internal function]: App\Controllers\Api\Frontend\Customer\Orders\CreateController->route('memmingen')
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen')
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2013-03-22 13:10:47] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php line 297' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php:297
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(297): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/Users/johannes...', 297, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(81): App\Controllers\Api\Frontend\Customer\Orders\CreateController->checkIngredientModelIdsAreValid()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(37): App\Controllers\Api\Frontend\Customer\Orders\CreateController->checkModelIds()
#3 [internal function]: App\Controllers\Api\Frontend\Customer\Orders\CreateController->route('memmingen')
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen')
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2013-03-22 13:13:39] log.ERROR: exception 'ErrorException' with message 'Warning: Invalid argument supplied for foreach() in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php line 295' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php:295
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(295): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'Invalid argumen...', '/Users/johannes...', 295, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(81): App\Controllers\Api\Frontend\Customer\Orders\CreateController->checkIngredientModelIdsAreValid()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(37): App\Controllers\Api\Frontend\Customer\Orders\CreateController->checkModelIds()
#3 [internal function]: App\Controllers\Api\Frontend\Customer\Orders\CreateController->route('memmingen')
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen')
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2013-03-22 18:17:20] log.ERROR: exception 'ErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Illuminate\Validation\Factory::make() must be of the type array, boolean given, called in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 169 and defined in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php line 62' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php:62
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php(62): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(4096, 'Argument 1 pass...', '/Users/johannes...', 62, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(169): Illuminate\Validation\Factory->make(false, Array)
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php(48): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/common/BaseApiController.php(48): Illuminate\Support\Facades\Validator::make(false, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/PaypalController.php(26): App\Controllers\Api\Common\BaseApiController->validateInput(Array)
#5 [internal function]: App\Controllers\Api\Services\PaypalController->saveToken()
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('saveToken', Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'saveToken', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(72): call_user_func_array(Object(Closure), Array)
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(463): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(448): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-03-22 18:20:41] log.ERROR: exception 'Exception' with message 'Authentication/Authorization Failed: You do not have permissions to make this API call' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/payment/PaypalService.php:198
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/payment/PaypalService.php(141): App\Controllers\Services\Payment\PaypalService::callApi(Array, Array, 'https://api-3t....')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/payment/PaypalService.php(112): App\Controllers\Services\Payment\PaypalService::callApiWithAuthHeader(Array, 'timestamp=13639...')
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(159): App\Controllers\Services\Payment\PaypalService::getCheckoutUrl(Object(App\Models\OrderModel))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(45): App\Controllers\Api\Frontend\Customer\Orders\CreateController->computePaymentMethod()
#4 [internal function]: App\Controllers\Api\Frontend\Customer\Orders\CreateController->route('memmingen')
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(927): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen')
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(72): call_user_func_array(Object(Closure), Array)
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(958): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(463): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(448): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#15 {main} [] []
[2013-03-22 20:07:51] log.ERROR: exception 'Exception' with message 'Authentication/Authorization Failed: You do not have permissions to make this API call' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/payment/PaypalService.php:198
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/payment/PaypalService.php(141): App\Controllers\Services\Payment\PaypalService::callApi(Array, Array, 'https://api-3t....')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/payment/PaypalService.php(112): App\Controllers\Services\Payment\PaypalService::callApiWithAuthHeader(Array, 'timestamp=13639...')
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(159): App\Controllers\Services\Payment\PaypalService::getCheckoutUrl(Object(App\Models\OrderModel))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/customer/orders/CreateController.php(45): App\Controllers\Api\Frontend\Customer\Orders\CreateController->computePaymentMethod()
#4 [internal function]: App\Controllers\Api\Frontend\Customer\Orders\CreateController->route('memmingen')
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6979): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen')
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12999): call_user_func_array(Object(Closure), Array)
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12980): Illuminate\Routing\Route->callCallable()
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6999): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#15 {main} [] []
